name: skasio_markr

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: markr_prod
      POSTGRES_PASSWORD: CpfzDA3nR3jH9Ky4
      POSTGRES_DB: markr
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: markr-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/markr
      SPRING_DATASOURCE_USERNAME: markr_prod
      SPRING_DATASOURCE_PASSWORD: CpfzDA3nR3jH9Ky4

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: markr-tests
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      SPRING_DATASOURCE_USERNAME: markr_test
      SPRING_DATASOURCE_PASSWORD: DekqFAQnRIjH2Kz1
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: false
      SPRING_PROFILES_ACTIVE: test
    command: ./mvnw test -P test

volumes:
  postgres_data:
    name: markr_postgres_data
